import restrictedGlobals from "confusing-browser-globals";

export default {
  // Possible Errors
  "for-direction": "error",
  "getter-return": "error",
  "no-async-promise-executor": "error",
  "no-await-in-loop": "error",
  "no-compare-neg-zero": "error",
  "no-cond-assign": "error",
  "no-console": "error",
  "no-constant-condition": "error",
  "no-control-regex": "error",
  "no-debugger": "error",
  "no-dupe-args": "error",
  "no-dupe-else-if": "error",
  "no-dupe-keys": "error",
  "no-duplicate-case": "error",
  "no-empty": "error",
  "no-empty-character-class": "error",
  "no-ex-assign": "error",
  "no-extra-boolean-cast": "error",
  "no-extra-parens": ["error", "all", { ignoreJSX: "all" }],
  "no-extra-semi": "error",
  "no-func-assign": "error",
  "no-import-assign": "error",
  "no-inner-declarations": "error",
  "no-invalid-regexp": "error",
  "no-irregular-whitespace": "error",
  "no-misleading-character-class": "error",
  "no-obj-calls": "error",
  "no-prototype-builtins": "error",
  "no-regex-spaces": "error",
  "no-setter-return": "error",
  "no-sparse-arrays": "error",
  "no-template-curly-in-string": "error",
  "no-unexpected-multiline": "error",
  "no-unreachable": "error",
  "no-unsafe-finally": "error",
  "no-unsafe-negation": "error",
  "no-useless-backreference": "error",
  "require-atomic-updates": "error",
  "use-isnan": "error",
  "valid-typeof": "error",
  // Best Practices
  "accessor-pairs": "error",
  "array-callback-return": "error",
  "block-scoped-var": "error",
  "class-methods-use-this": "error",
  complexity: ["error", 10],
  "consistent-return": "error",
  curly: "error",
  "default-case": "error",
  "dot-location": ["error", "property"],
  "dot-notation": "error",
  eqeqeq: "error",
  "guard-for-in": "error",
  "max-classes-per-file": "error",
  "no-alert": "error",
  "no-caller": "error",
  "no-case-declarations": "error",
  "no-div-regex": "error",
  "no-else-return": "error",
  "no-empty-function": "error",
  "no-empty-pattern": "error",
  "no-eq-null": "error",
  "no-eval": "error",
  "no-extend-native": "error",
  "no-extra-bind": "error",
  "no-extra-label": "error",
  "no-fallthrough": "error",
  "no-floating-decimal": "error",
  "no-global-assign": "error",
  "no-implicit-coercion": "error",
  "no-implicit-globals": "error",
  "no-implied-eval": "error",
  "no-invalid-this": "error",
  "no-iterator": "error",
  "no-labels": "error",
  "no-lone-blocks": "error",
  "no-loop-func": "error",
  "no-magic-numbers": "off",
  "no-multi-spaces": "error",
  "no-multi-str": "error",
  "no-new": "error",
  "no-new-func": "error",
  "no-new-wrappers": "error",
  "no-octal": "error",
  "no-octal-escape": "error",
  "no-param-reassign": "error",
  "no-proto": "error",
  "no-redeclare": "error",
  "no-restricted-properties": "off",
  "no-return-assign": "error",
  "no-return-await": "error",
  "no-script-url": "error",
  "no-self-assign": "error",
  "no-self-compare": "error",
  "no-sequences": "error",
  "no-throw-literal": "error",
  "no-unmodified-loop-condition": "error",
  "no-unused-expressions": "error",
  "no-unused-labels": "error",
  "no-useless-call": "error",
  "no-useless-catch": "error",
  "no-useless-concat": "error",
  "no-useless-escape": "error",
  "no-useless-return": "error",
  "no-void": "error",
  "no-warning-comments": "error",
  "no-with": "error",
  "prefer-named-capture-group": "off",
  "prefer-promise-reject-errors": "error",
  radix: "error",
  "require-await": "error",
  "require-unicode-regexp": "error",
  "vars-on-top": "error",
  "wrap-iife": "error",
  yoda: "error",
  // Strict Mode
  strict: ["error", "global"],
  // Variables
  "init-declarations": "error",
  "no-delete-var": "error",
  "no-label-var": "error",
  "no-restricted-globals": ["error"].concat(restrictedGlobals),
  "no-shadow": "error",
  "no-shadow-restricted-names": "error",
  "no-undef": "error",
  "no-undef-init": "error",
  "no-undefined": "error",
  "no-unused-vars": "error",
  "no-use-before-define": "error",
  // Node.js and CommonJS
  "callback-return": ["error", ["callback", "cb", "done", "next"]],
  "global-require": "error",
  "handle-callback-err": ["error", "^(e|err|error)$"],
  "no-buffer-constructor": "error",
  "no-mixed-requires": ["error", { allowCall: true }],
  "no-new-require": "error",
  "no-path-concat": "error",
  "no-process-env": "error",
  "no-process-exit": "error",
  "no-restricted-modules": "off",
  "no-sync": "error",
  // ECMAScript 6
  "arrow-body-style": "error",
  "arrow-parens": ["error", "as-needed"],
  "arrow-spacing": "error",
  "constructor-super": "error",
  "generator-star-spacing": "error",
  "no-class-assign": "error",
  "no-confusing-arrow": "off",
  "no-const-assign": "error",
  "no-dupe-class-members": "error",
  "no-duplicate-imports": ["error", { includeExports: true }],
  "no-new-symbol": "error",
  "no-restricted-imports": "off",
  "no-this-before-super": "error",
  "no-useless-computed-key": "error",
  "no-useless-constructor": "error",
  "no-useless-rename": "error",
  "no-var": "error",
  "object-shorthand": "error",
  "prefer-arrow-callback": "error",
  "prefer-const": "error",
  "prefer-destructuring": "error",
  "prefer-numeric-literals": "off",
  "prefer-rest-params": "error",
  "prefer-spread": "error",
  "prefer-template": "error",
  "require-yield": "error",
  "rest-spread-spacing": "error",
  "sort-imports": "error",
  "symbol-description": "error",
  "template-curly-spacing": "error",
  "yield-star-spacing": "error",
  // https://github.com/facebook/react/tree/master/packages/eslint-plugin-react-hooks
  "react-hooks/exhaustive-deps": "warn",
  "react-hooks/rules-of-hooks": "error",
  // https://github.com/yannickcr/eslint-plugin-react/tree/master/docs/rules
  "react/react-in-jsx-scope": "off",
  // https://github.com/evcohen/eslint-plugin-jsx-a11y/tree/master/docs/rules
  "jsx-a11y/anchor-is-valid": [
    "error",
    {
      aspects: ["invalidHref", "preferButton"],
      components: ["Link"],
    },
  ],
};
